version: '3.8'

services:
  llm-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${MODEL_NAME:-microsoft/DialoGPT-medium}
      - QUANTIZATION_ENABLED=${QUANTIZATION_ENABLED:-false}
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
